import './globals.css'
import { Inter } from 'next/font/google'
import { library } from '@fortawesome/fontawesome-svg-core';
import { faDesktop, faCog, faAddressCard } from '@fortawesome/free-solid-svg-icons';
import Navigation from './components/Navigation';

library.add(faDesktop, faCog, faAddressCard);


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className='flex items-center justify-between'>
        <Navigation />
        {children}
        </main>
      
        </body>
    </html>
  )
}
